### ISSUE TITLE
`Client` of undefined

### ISSUE THREAD

**Issue by FalloutPL** [ozum/pg-generator#17]
```
C:\praca\cloudAdmin>pgen exec sequelize-template -d yyy-u uuu-p xxx-t model
info: Executing command: pgen.js exec sequelize-template --host localhost --port 5432 --user uuu --database yyy --schema public --target model --log info --extension nunj.html --indent 4
error: TypeError: Cannot read property 'Client' of undefined
    at C:\Program Files\nodejs\node_modules\pg-generator\node_modules\pg-structure\lib\pg-structure.js:54:28
    at getClient (C:\Program Files\nodejs\node_modules\pg-generator\node_modules\pg-structure\lib\pg-structure.js:52:12)
    at C:\Program Files\nodejs\node_modules\pg-generator\node_modules\pg-structure\lib\pg-structure.js:195:44
    at process._tickCallback (node.js:402:9)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:140:18)
    at node.js:1001:3
```
any ideas?

```
node = 5.6.0
npm = 3.7.2
```

**Comment by ozum** [comment]
Hi,

No idea, I need more details. Could you please provide
* pg-generator version,
* a sample db,
* small code which reproduces given error.

**Comment by ozum** [comment]
Is `pg` module available in your project's node_modules directory? Related line is simply as below:

```js
try {
    var pg  = require('pg').native;
} catch (err) {
    pg      = require('pg');
}

// And later in line 54:
let client = new pg.Client(pgOptions);
```

**Comment by nVVEBd** [comment]
Have the same problem with v2.0.20 -> v 3.0.1 has this problem -> https://github.com/ozum/pg-generator/issues/19

**Comment by ozum** [comment]
Could you please change node_modules/pg-structure/lib/pg-structure.js as below and tell me whether it works?

```js
try {
    var pg  = require('pg').native || require('pg');
} catch (err) {
    pg      = require('pg');
}
```

**Comment by nVVEBd** [comment]
I'm trying to change but every time I change and save with nano the file gets overwritten. With the standard.

**Comment by ozum** [comment]
I could not reproduce it. In any case I updated `pg-structure` as below.

```js
try {
    var pg  = require('pg').native || require('pg');
} catch (err) {
    pg      = require('pg');
}
```

If this issue appears again, please open a new ticket.
