### ISSUE TITLE
Error with pgen exec sequelize-template

### ISSUE THREAD

**Issue by nVWEBd** [ozum/pg-generator#20]
I stumbled upon an error when trying to generate the models for my postgresql database:

```
error: Template render error: (/Users/nvukovic/securityadvisor/usr/local/X/Frontend_node/sequelize-template/table/definition/{table.name}.js.nunj.html) [Line 6, Column 39]
  Template render error: (/Users/nvukovic/securityadvisor/usr/local/X/Frontend_node/sequelize-template/table/definition/{table.name}.js.nunj.html)
  Template render error: (/Users/nvukovic/securityadvisor/usr/local/X/Frontend_node/sequelize-template/table/definition/{table.name}.js.nunj.html)
  Template render error: (/Users/nvukovic/securityadvisor/usr/local/X/Frontend_node/sequelize-template/partials/columns.nunj.html) [Line 3, Column 45]
  TypeError: Cannot read property 'columns' of undefined
    at Object.exports.prettifyError (/Users/nvukovic/.npm/lib/node_modules/pg-generator/node_modules/nunjucks/src/lib.js:34:15)
    at /Users/nvukovic/.npm/lib/node_modules/pg-generator/node_modules/nunjucks/src/environment.js:485:31
    at root [as rootRenderFunc] (eval at <anonymous> (/Users/nvukovic/.npm/lib/node_modules/pg-generator/node_modules/nunjucks/src/environment.js:564:24), <anonymous>:182:3)
    at Obj.extend.render (/Users/nvukovic/.npm/lib/node_modules/pg-generator/node_modules/nunjucks/src/environment.js:478:15)
    at /Users/nvukovic/.npm/lib/node_modules/pg-generator/lib/index.js:105:58
    at PGGenerator._write.Promise [as _write] (/Users/nvukovic/.npm/lib/node_modules/pg-generator/lib/index.js:92:12)
    at Walker.<anonymous> (/Users/nvukovic/.npm/lib/node_modules/pg-generator/lib/index.js:192:60)
    at emitNone (events.js:67:13)
    at Walker.emit (events.js:166:7)
```

Which results in NO 

> /models/definition/*.js

 files created...

Any help would go a mile now.

**Comment by ozum** [comment]
That is a too generic error. I need a db schema which reproduces this error to debug it.

**Comment by nVVEBd** [comment]
What do you need exactly?

**Comment by ozum** [comment]
- DDL/SQL for creating a db,
- `pg-generator` command executed which reproduces this error for given db.

DDL example:
```SQL
CREATE TABLE "company"(
 "id" Serial NOT NULL,
 "owner_id" Integer,
 "created_at" Timestamp(0) DEFAULT now() NOT NULL,
 "updated_at" Timestamp(0) DEFAULT now() NOT NULL,
 "name" Character varying(20) NOT NULL,
 "income" Integer
);
```

**Comment by nVVEBd** [comment]
```
pgen template sequelize -t sequelize-template

pgen exec sequelize-template -d database -u user -p password -t sequelize-template/models
```

This is what I ran. To create the models for an existing PGSQL.

**Comment by ozum** [comment]
As I said in my previous message, I need a database which produces given error.

**Comment by geoffba** [comment]
I had the same error, and fixed by uninstalling locally and reinstalling pg-generator globally (which pg-gen does say it prefers)

**Comment by ozum** [comment]
@geoffba it would be good to have a DDL schema which reproduces given error for me to fix this bug.
