### ISSUE TITLE
Unexpected token illegal error on template copy

### ISSUE THREAD

**Issue by jeremypokeefe** [ozum/pg-generator#23]
After entering the first command to copy the buit-in template is entered `pgen template sequelize -t sequelize-template`, I receive this error in return.

/usr/local/lib/node_modules/pg-generator/lib/bin/pgen.js:47
    .option('-c, --clear', `${theme.danger('Caution!')} Deletes all files in t
                           ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

I've attempted removing and re-installing the package, but nothing changed.

**Comment by jeremypokeefe** [comment]
This error is only displayed if you have an outdated version of Node.JS. I upgraded node and the error disappeared.

**Comment by rbecheras** [comment]
pg-generator need node>=v4.0.0
