### ISSUE TITLE
Error: error: value for domain information_schema.yes_or_no

### ISSUE THREAD

**Issue by pda2564** [ozum/pg-generator#43]
Hi all, 
I tried to gen models from postgre local with this command:
`PS D:\...> pgen exec sequelize-template -d helloworld -u postgres -p etvp@#4312 -t model --optionsfile options.js`
However I got an error sayings:
```
info: Executing command: pgen.js exec sequelize-template --host localhost --port 5432 --user postgres --database helloworld --schema public --target model --log info --extension nunj.html --indent 4 --optionsfile options.js
error: Error: error: value for domain information_schema.yes_or_no violates check constraint "yes_or_no_check"
    at Query.query.on (C:\Users\Ah\AppData\Roaming\npm\node_modules\pg-generator\node_modules\pg-structure\lib\pg-structure.js:78:24)
    at emitOne (events.js:96:13)
    at Query.emit (events.js:188:7)
    at Query.handleError (C:\Users\Ah\AppData\Roaming\npm\node_modules\pg-generator\node_modules\pg-structure\node_modules\pg\lib\query.js:143:8)
    at Connection.<anonymous> (C:\Users\Ah\AppData\Roaming\npm\node_modules\pg-generator\node_modules\pg-structure\node_modules\pg\lib\client.js:180:26)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:188:7)
    at Socket.<anonymous> (C:\Users\Ah\AppData\Roaming\npm\node_modules\pg-generator\node_modules\pg-structure\node_modules\pg\lib\connection.js:136:12)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
```
Anyone know where it comes from? and why?
Thank a lot!

**Comment by ozum** [comment]
Hi,

If you could share a basic DDL of a database, I could try to debug.

Kind regards,

**Comment by pda2564** [comment]
Thank you so much for quick reply.
Here is the sql I dumped. It's quite complex.
You can run it with pgAdmin to restore DB, and view its definition and relations.
`https://drive.google.com/file/d/0B0Q0TsezIq1ceFdXM1p5S00xLUU/view?usp=sharing.`
Please try to debug.
Thanks again.

**Comment by ozum** [comment]
Hi,

Please uninstall and reinstall `pg-generator` as follows. (Use `sudo` if necessary depending on your environment.)

```
$ npm uninstall -g pg-generator
$ npm install -g pg-generator
```

There was a typo in `pg-structure` which is one of the dependencies of `pg-generator`. I corrected `pg-structure` and submitted new version (`3.5.15`) to npm.

I tested new version with your database, it seems working. If problem persists, please make sure you are using `pg-structure` v.3.5.15 in `node_modules` of `pg-generator`.

Kind Regards,

**Comment by pda2564** [comment]
Fantastic!  Thanks a lot! I'll try your instruction and will contact if have any issues.

**Comment by pda2564** [comment]
It worked. Thanks!
