### ISSUE TITLE
`TypeError: query.on is not a function`

### ISSUE THREAD

**Issue by jake-lambert-volusion** [ozum/pg-generator#66]
Hello,

I've followed the instructions at http://www.pg-generator.com/#sequelize-example and got the following error (I did not use global installs).

```
/Users/jake.lambert/Documents/repos/volusion-api-v2/node_modules/pg-generator/lib/bin/pgen.js:304
    query.on('row', row => databases.push(row.datname));
          ^

TypeError: query.on is not a function
    at db (/Users/jake.lambert/Documents/repos/volusion-api-v2/node_modules/pg-generator/lib/bin/pgen.js:304:11)
    at /Users/jake.lambert/Documents/repos/volusion-api-v2/node_modules/pg-generator/lib/bin/pgen.js:294:12
    at Connection.<anonymous> (/Users/jake.lambert/Documents/repos/volusion-api-v2/node_modules/pg/lib/client.js:214:7)
    at Object.onceWrapper (events.js:313:26)
    at Connection.emit (events.js:228:7)
    at Socket.<anonymous> (/Users/jake.lambert/Documents/repos/volusion-api-v2/node_modules/pg/lib/connection.js:126:12)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
```

Per this [stackoverflow](https://stackoverflow.com/questions/45329461/query-on-is-not-a-function.) the query.on api was removed from pg in version 7, however this lib has pg 7 as a dep.

**Comment by ozum** [comment]
Thanks for reporting. I updated 'pg-generator'.

Could you please try with latest version and report whether the problem still exist?

**Comment by jake-lambert-volusion** [comment]
Thanks for the super quick reply!

Looks like that is cleared up. Now I'm seeing something like the following. Would this be an indication something is wrong with my config and it can't connect to postgres (which I don't think is the case, but you never know...)?

```
info: Starting to walk template directory: '/Users/jake.lambert/Documents/repos/volusion-api-v2/sequelize-template' for target directory '/Users/jake.lambert/Documents/repos/volusion-api-v2/testm'
/Users/jake.lambert/Documents/repos/volusion-api-v2/node_modules/nunjucks/src/environment.js:556
          throw err;
          ^

Template render error: (/Users/jake.lambert/Documents/repos/volusion-api-v2/sequelize-template/db/relation-cheatsheet.txt.nunj.html)
  TypeError: Cannot read property 'foreignKeyConstraints' of null
    at Object._prettifyError (/Users/jake.lambert/Documents/repos/volusion-api-v2/node_modules/nunjucks/src/lib.js:36:11)
    at /Users/jake.lambert/Documents/repos/volusion-api-v2/node_modules/nunjucks/src/environment.js:561:19
    at eval (eval at _compile (/Users/jake.lambert/Documents/repos/volusion-api-v2/node_modules/nunjucks/src/environment.js:631:18), <anonymous>:12:11)
    at /Users/jake.lambert/Documents/repos/volusion-api-v2/node_modules/nunjucks/src/environment.js:611:9
    at Template.root [as rootRenderFunc] (eval at _compile (/Users/jake.lambert/Documents/repos/volusion-api-v2/node_modules/nunjucks/src/environment.js:631:18), <anonymous>:122:3)
    at Template.getExported (/Users/jake.lambert/Documents/repos/volusion-api-v2/node_modules/nunjucks/src/environment.js:609:10)
    at eval (eval at _compile (/Users/jake.lambert/Documents/repos/volusion-api-v2/node_modules/nunjucks/src/environment.js:631:18), <anonymous>:11:5)
    at Environment.getTemplate (/Users/jake.lambert/Documents/repos/volusion-api-v2/node_modules/nunjucks/src/environment.js:277:9)
    at Template.root [as rootRenderFunc] (eval at _compile (/Users/jake.lambert/Documents/repos/volusion-api-v2/node_modules/nunjucks/src/environment.js:631:18), <anonymous>:9:5)
    at Template.render (/Users/jake.lambert/Documents/repos/volusion-api-v2/node_modules/nunjucks/src/environment.js:550:10) {
  lineno: 9,
  colno: 106,
  firstUpdate: true,
  Update: [Function: Update]
}
```

**Comment by ozum** [comment]
It doesn't seem a connection problem.

You may have PostgreSQL schemas other than `public` and some foreign key is referring other schema. If this is the case use `--schema public,my_other_schema,some_schema` option.

Also, to test whether it is a config problem, test with a very simple database in same PostgreSQL server.

Otherwise I need `pgen` command executed and a database schema (ddl) producing the error to investigate the problem. If you provide a database schema, please provide as few db objects as possible to ease my debugging please.
